language: scala
jdk: openjdk8
script:
  if [[ ! -z "$TRAVIS_TAG" ]]; then ./publish.sh; else ./make.sh; fi
sudo: false
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/1.0"
    - "$HOME/.sbt/boot"
    - "$HOME/.sbt/preloaded"
    - "$HOME/.embedpostgresql"
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
before_install:
  - openssl aes-256-cbc -K $encrypted_a4f2ea8de7e1_key -iv $encrypted_a4f2ea8de7e1_iv -in rings.tar.enc -out rings.tar -d
  - tar xvf rings.tar
git:
  depth: false
branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/
    - /^hotfix\/.*$/
    - /^hotfix\/.*$/
    - /^\d+\.\d+(\.\d+)?$/
